# Generated by Django 5.2.1 on 2025-07-03 22:31

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0005_remove_atencion_doctor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detallepago',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, help_text='Subtotal calculado automáticamente, considerando seguro y descuento.', max_digits=10, verbose_name='Subtotal'),
        ),
    ]
