# Generated by Django 5.2.1 on 2025-07-04 12:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_tipogasto_remove_doctor_duracion_cita_and_more'),
        ('doctor', '0006_alter_detallepago_subtotal'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='citamedica',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='citamedica',
            name='doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='citas', to='core.doctor', verbose_name='Doctor'),
        ),
        migrations.AddField(
            model_name='horarioatencion',
            name='doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='horarios', to='core.doctor', verbose_name='Doctor'),
        ),
        migrations.AlterUniqueTogether(
            name='citamedica',
            unique_together={('doctor', 'fecha', 'hora_cita')},
        ),
    ]
